[package]
name = "dynno_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full"]}
quote = "1"
proc-macro2 = "1"
dynno_core = {path = "../dynno_core" }
toml = "1.1.2"
proc-macro-crate = {version = "3"}
uuid = { version = "1.23.4", features = ["v4"] }
